### PR TITLE
[fix] change behaviour of `FindFiles` to ignore errors 

### LINKED ISSUE #99: FindFiles exits and returns no files when it can't open a directory
This program

```
package main

import (
	"log"
	"os"

	"github.com/bitfield/script"
)

func main() {
	h, err := os.UserHomeDir()
	if err != nil {
		log.Fatal(err)
	}
	_, err = script.FindFiles(h).Stdout()
	if err != nil {
		log.Fatal(err)
	}
}
```

yields:

```
$ go build
$ ./script
2022/03/12 11:51:51 open /Users/user/.Trash: operation not permitted
```

I expected behavior similar to `find $HOME -type f`, i.e. to return files from directories it can open.

### PR DESCRIPTION
**Pull request by mahadzaryab1**
- Replaced `filepath.Walk` with the newer `fs.WalkDir`
- Changed the behaviour of `FindFiles` to only return an error if no paths were found
- Fixes #99

### CODE REVIEW

**Comment by mahadzaryab1** [comment]
@bitfield Do you have any thoughts on how we should test the case where there is an error but we get more than one path?

**Comment by bitfield** [comment]
That's a tricky one! What about creating a tempdir and then setting up files `a`, `b`, and `c` within it, of which the permissions of `c` are `0o000`? Would that work?

**Comment by mahadzaryab1** [comment]
> That's a tricky one! What about creating a tempdir and then setting up files `a`, `b`, and `c` within it, of which the permissions of `c` are `0o000`? Would that work?

@bitfield I gave it a shot but I can't seem to produce that case. Changing the permissions of the file doesn't prevent the path from being listed. Let me know if you have any thoughts on how to proceed.

**Comment by bitfield** [comment]
Remember `fs.WalkDir` only calls your func for directories. It doesn't try to read files, so you won't ever receive a non-nil error for permissions on a _file_, only on a directory.

**Comment by mahadzaryab1** [comment]
@bitfield added a test case - can you take another look?

File: script_test.go [hunk 1]
```diff
@@ -1286,6 +1286,39 @@ func TestFindFiles_InNonexistentPathReturnsError(t *testing.T) {
...
+	}
+	restrictedDirPath := filepath.Join(tmpDir, "restricted_dir")
+	if err := os.Mkdir(restrictedDirPath, os.ModePerm); err != nil {
+		t.Fatal(err)
+	}
+	fileBPath := filepath.Join(restrictedDirPath, "file_b.txt")
+	if err := os.WriteFile(fileBPath, []byte("hello again!"), os.ModePerm); err != nil {
+		t.Fatal(err)
+	}
+	if err := os.Chmod(restrictedDirPath, 0o000); err != nil {
```
Comment (mahadzaryab1) [inline script_test.go:1304]: @bitfield this test fails on windows since chmod is a unix command. thoughts on how to proceed? should we make this a unix-only test?

Comment (bitfield) [reply script_test.go:1304]: Yes, Windows doesn't have the concept of file permissions as Go understands them—this is Unix-only.

File: script_test.go [hunk 2]
```diff
@@ -1286,6 +1286,39 @@ func TestFindFiles_InNonexistentPathReturnsError(t *testing.T) {
...
+		t.Fatal(err)
+	}
+	t.Cleanup(func() { os.Chmod(restrictedDirPath, os.ModePerm) })
```
Comment (bitfield) [inline script_test.go:1307]: This tempdir will be deleted anyway.

File: script_test.go [hunk 3]
```diff
@@ -1286,6 +1286,39 @@ func TestFindFiles_InNonexistentPathReturnsError(t *testing.T) {
...
+	p := script.FindFiles(tmpDir)
```
Comment (bitfield) [inline script_test.go:1308]:
```suggestion
	got, err := script.FindFiles(tmpDir).String()
```

File: script_test.go (hunk 2 above)
Comment (mahadzaryab1) [reply script_test.go]: @bitfield I need to do this so that this dir can get cleaned up. Otherwise, the cleanup function throws a permissions error. Let me know if you'd like to do this a different way. 
```
TempDir RemoveAll cleanup: openfdat /var/folders/mn/31m4g_6j7qz26m7_00mgsbrc0000gn/T/TestFindFiles_DoesNotErrorWhenSubDirectoryIsNotReadable1455531535/001/restricted_dir: permission denied
```

Comment (bitfield) [reply script_test.go]: That's because you're also creating a file _inside_ the restricted directory. So `RemoveAll` isn't able to delete the file, because that requires modifying the directory, which you don't have permission to do.

You don't need this file for the test (and `FindFIles` won't be able to even know it exists, because of the directory permissions). Without the file, you don't need the `Cleanup` func, because the automatic `RemoveAll` succeeds.

**Comment by bitfield** [comment]
This test covers the case where the induced error is on the last path that `FindFiles` visits. Unfortunately, this just happens to miss a logic bug in the implementation of `FindFiles`. If you change the test (for example, renaming `restricted_dir` to `a_restricted_dir`, so that it's visited before `file_a`), you'll see what I mean.

File: script_test.go (hunk 2 above)
Comment (mahadzaryab1) [reply script_test.go]: @bitfield If I don't add the file - then wouldn't the test pass regardless because FindFiles doesn't print directories. I was trying to show that there's a path inside the restricted dir that is not printed.

**Comment by mahadzaryab1** [comment]
> This test covers the case where the induced error is on the last path that `FindFiles` visits. Unfortunately, this just happens to miss a logic bug in the implementation of `FindFiles`. If you change the test (for example, renaming `restricted_dir` to `a_restricted_dir`, so that it's visited before `file_a`), you'll see what I mean.

Ah okay I see. I added a check in `FindFiles` to skip the directory if its a permission error. What do you think?

File: script_test.go (hunk 2 above)
Comment (bitfield) [reply script_test.go]: Well, according to your test name, the _test_ is about whether or not `FindFiles` returns an error if it encounters one on its walk. If the error happens to be "can't list files in directory", then we hardly need to test that `FindFIles` doesn't return those files: how could it? Testing the impossible doesn't catch bugs (testing _assumptions_, on the other hand, is an excellent idea and we should always do it).

**Comment by bitfield** [comment]
Well, I don't think it matters what the error is. The point is that if we encounter _any_ errors during the walk, we should only report them if we haven't also found some valid files.

**Comment by mahadzaryab1** [comment]
> Well, I don't think it matters what the error is. The point is that if we encounter _any_ errors during the walk, we should only report them if we haven't also found some valid files.

I see - should we then always return `fs.SkipDir` when we encounter an error during the walk?

File: script_test.go (hunk 2 above)
Comment (mahadzaryab1) [reply script_test.go]: @bitfield got it - thanks for the explanation! i removed the file for the test

**Comment by bitfield** [comment]
> should we then always return `fs.SkipDir` when we encounter an error during the walk?

Well, there are only four possibilities:

1. Return `SkipAll` - that's no good, because it stops walking altogether
2. Return the error - ditto
3. Return `nil` - no good, because it loses the error
4. Return `SkipDir`

So I don't think we actually have a choice to make here, unless there's another possibility you can think of?

**Comment by mahadzaryab1** [comment]
> > should we then always return `fs.SkipDir` when we encounter an error during the walk?
> 
> Well, there are only four possibilities:
> 
> 1. Return `SkipAll` - that's no good, because it stops walking altogether
> 2. Return the error - ditto
> 3. Return `nil` - no good, because it loses the error
> 4. Return `SkipDir`
> 
> So I don't think we actually have a choice to make here, unless there's another possibility you can think of?

@bitfield Good point. But if we always run `SkipDir`, then we lose the error as well because WalkDir will swallow the error.

**Comment by bitfield** [comment]
Right. But the `WalkFunc` can be a closure, so we can save the error in some variable in the outer scope before returning `SkipDir`.

**Comment by mahadzaryab1** [comment]
> Right. But the `WalkFunc` can be a closure, so we can save the error in some variable in the outer scope before returning `SkipDir`.

@bitfield Addressed. Let me know what you think.

**Comment by bitfield** [comment]
Great! This code looks solid. Would you like to update the documentation a little to explain this (sensible, but non-obvious) error behaviour?

**Comment by mahadzaryab1** [comment]
> Great! This code looks solid. Would you like to update the documentation a little to explain this (sensible, but non-obvious) error behaviour?

Done!

File: script.go [hunk 4]
```diff
@@ -76,8 +77,12 @@ func File(path string) *Pipe {
 }
 
 // FindFiles creates a pipe listing all the files in the directory dir and its
-// subdirectories recursively, one per line, like Unix find(1). If dir doesn't
-// exist or can't be read, the pipe's error status will be set.
+// subdirectories recursively, one per line, like Unix find(1).
+// If an error occurs while reading the directory, the behaviour is as follows:
```
Comment (bitfield) [inline script.go:81]: This is good, but I think we can be a bit more concise. What about:

```
// Errors are ignored unless no files are found (in which case the pipe's error
// status will be set to the last error encountered). 
```

Comment (mahadzaryab1) [reply script.go]: @bitfield done!

**Comment by bitfield** [comment]
Super nice! Thanks for steering this one, great work.
